### ISSUE TITLE
New project autohinting - how to address existing fpgm, prep, and glyf program data

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#19]
When I follow these steps with an unhinted variable font:

>1. Start Visual True Type.
>2. File > Open. Navigate to font file you would like to Autohint.
>3. Select Font File and Open.
>4. From the Tools menu, select Autohint > Light Latin Autohint.
>5. When Autohinting is complete choose Save from File Menu

I receive the VTT prompt: "Do you wish to import Font Program, Pre-program, and Glyph program source from associated binary data?" => Yes/No

It isn't clear why this pops up because there is no fpgm table, prep table, cvt table, cvar table, or glyf table opcodes in the varfont binary.  My guess is that the answer is always "No" in a new VTT autohint setup?  If so, it would be useful to state this in the same section.

**Comment by dberlow** [comment]
Those are the 5 required tt tables for a vf, so they must end up in the hinted font.

On Sep 22, 2021, at 3:10 PM, Chris Simpkins ***@***.***> wrote:

﻿
When I follow these steps with an unhinted variable font:

Start Visual True Type.
File > Open. Navigate to font file you would like to Autohint.
Select Font File and Open.
From the Tools menu, select Autohint > Light Latin Autohint.
When Autohinting is complete choose Save from File Menu
I receive the VTT prompt: "Do you wish to import Font Program, Pre-program, and Glyph program source from associated binary data?" => Yes/No

It isn't clear why this pops up because there is no fpgm table, prep table, cvt table, cvar table, or glyf table opcodes in the varfont binary. My guess is that the answer is always "No" in a new VTT autohint setup? If so, it would be useful to state this in the same section.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mikedug** [comment]
I will need to document this. I am not sure why VTT shows this prompt, when Autohinting a new font, as the Autohinter generates these tables along with the new hints.

**Comment by dberlow** [comment]
Is it about adding tsi tables?

On Sep 22, 2021, at 3:40 PM, Michael Duggan ***@***.***> wrote:

﻿
I will need to document this. I am not sure why VTT shows this prompt, when Autohinting a new font, as the Autohinter generates these tables along with the new hints.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrissimpkins** [comment]
I am running through Mike's docs with an un-hinted VF to review the current draft.  Adding any issues that I turn up in an end-to-end run through the README.  The issue in this thread occurs when you **open** the un-hinted font in VTT.  There is no save involved at this stage.  If the data are not there on read, my guess is that selecting Yes in the dialog causes no harm.  But I don't know if this configures any part of the automated hinting execution to use pre-existing data which is likely not desirable.

**Comment by mikedug** [comment]
https://docs.microsoft.com/en-us/typography/tools/vtt/

This was introduced in Version 6.01 [August 31, 2015 release]. 
Import binary font hints. When opening fonts without VTT source data, you can import the binary data to low-level code you can edit. Later a checkbox was added to suppress this message

**Version 6.10 [February, 2016 release]**
Check box added to allow future suppression of Import binary hints message when opening a font with no source data.

I will update the document to make it clear that when preparing to Autohint a font, the answer should be no.

**Comment by dberlow** [comment]
Oh, I See now, thanks.

**Comment by mikedug** [comment]
Added more details about this message, instructions on how to disable it, and how to respond to it, when opening a new font.
